########## admin api ###########

### get method
GET http://localhost:8000/api/v1/admin/
### post admin method
POST http://localhost:8000/api/v1/admin/
Content-Type: application/json

{
    "fName": "Daeasdf",
    "lName": "Khatiwoda",
    "email": "sdfdsaussdfya@gmail.com",
    "phone": "1234567890",
    "address": "sydenn",
    "dob": "01/01/2020",
    "password": "1234"
}
### post admin email verification api
POST http://localhost:8000/api/v1/admin/email-verification
Content-Type: application/json

{
    "email": "kaushalya@gmail.com",
    "emailValidationCode" : "0efb974a-56da-4307-987b-d04ca30595cb"
}
### post admin login api
POST http://localhost:8000/api/v1/admin/login
Content-Type: application/json

{
    "email": "",
    "password" : ""
}

### get method
PATCH http://localhost:8000/api/v1/admin/

### patch admin api
PATCH http://localhost:8000/api/v1/admin/

#### $$$$$$$$$$$$$ CATEGORY SECTION $$$$$$$$$$$$$$ ####

### post new category
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "parentCatId" : "",
    "catName": "Small Appliances"
}

### get all active categories 
GET http://localhost:8000/api/v1/category

### update status of categories
PATCH  http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "_id": "62f07709ffc3a3ebb99c8be4",
    "status" : "active"
}

# ======= Product api
### post product
POST http://localhost:8000/api/v1/products
Content-Type: application/json

{
     "name": "iphone 13 pro", 
     "sku":"I-13", 
     "description": "lorem ipsum", 
     "qty": 100,  
     "price": 5000, 
     "salesPrice": 1000, 
     "salesDate": null
}

### get all products
GET http://localhost:8000/api/v1/products
