########## admin api ###########

### get method
GET http://localhost:8000/api/v1/admin/
### post admin method
POST http://localhost:8000/api/v1/admin/
Content-Type: application/json

{
    "fName": "Kaushalya",
    "lName": "Khatiwoda",
    "email": "kaushalya@gmail.com",
    "phone": "1234567890",
    "address": "sydenn",
    "dob": "01/01/2020",
    "password": "1234"
}
### post admin email verification api
POST http://localhost:8000/api/v1/admin/email-verification
Content-Type: application/json

{
    "email": "kaushalya@gmail.com",
    "emailValidationCode" : "3aab10bc-ef56-4be1-a9b4-5aded12dde8f"
}
### get method
PATCH http://localhost:8000/api/v1/admin/