########## admin api ###########

### get method
GET http://localhost:8000/api/v1/admin/
### post admin method
POST http://localhost:8000/api/v1/admin/
Content-Type: application/json

{
    "fName": "Daeasdf",
    "lName": "Khatiwoda",
    "email": "sdfdsaussdfya@gmail.com",
    "phone": "1234567890",
    "address": "sydenn",
    "dob": "01/01/2020",
    "password": "1234"
}
### post admin email verification api
POST http://localhost:8000/api/v1/admin/email-verification
Content-Type: application/json

{
    "email": "kaushalya@gmail.com",
    "emailValidationCode" : "0efb974a-56da-4307-987b-d04ca30595cb"
}
### post admin login api
POST http://localhost:8000/api/v1/admin/login
Content-Type: application/json

{
    "email": "",
    "password" : ""
}

### get method
PATCH http://localhost:8000/api/v1/admin/

### patch admin api
PATCH http://localhost:8000/api/v1/admin/

#### $$$$$$$$$$$$$ CATEGORY SECTION $$$$$$$$$$$$$$ ####

### post new category
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "parentCat" : "",
    "catName": "Laptops"
}
